import RPi.GPIO as GPIO

SHUTDOWN_LED = 2
SHUTDOWN_BUTTON = 3

MOTOR_LINE_ENABLE = 17
MOTOR_LINE_DIR = 27
MOTOR_LINE_STEP = 22
MOTOR_LINE_RELAY = 24

MOTOR_ROTOR_ENABLE = 10
MOTOR_ROTOR_DIR = 9
MOTOR_ROTOR_STEP = 11
MOTOR_ROTOR_RELAY = 23

SWITCH_OUT = 5
SWITCH_IN = 6

NEXTTABLE_LED = 19
NEXTTABLE_BUTTON = 26

def init():
    GPIO.setmode(GPIO.BCM)
    GPIO.setwarnings(False)

    GPIO.setup(SHUTDOWN_LED, GPIO.OUT)
    GPIO.setup(SHUTDOWN_BUTTON, GPIO.IN)

    GPIO.setup(MOTOR_LINE_ENABLE, GPIO.OUT)
    GPIO.setup(MOTOR_LINE_DIR, GPIO.OUT)
    GPIO.setup(MOTOR_LINE_STEP, GPIO.OUT)
    GPIO.setup(MOTOR_LINE_RELAY, GPIO.OUT)

    GPIO.setup(MOTOR_ROTOR_ENABLE, GPIO.OUT)
    GPIO.setup(MOTOR_ROTOR_DIR, GPIO.OUT)
    GPIO.setup(MOTOR_ROTOR_STEP, GPIO.OUT)
    GPIO.setup(MOTOR_ROTOR_RELAY, GPIO.OUT)

    GPIO.setup(SWITCH_OUT, GPIO.IN)
    GPIO.setup(SWITCH_IN, GPIO.IN)

    GPIO.setup(NEXTTABLE_LED, GPIO.OUT)
    GPIO.setup(NEXTTABLE_BUTTON, GPIO.IN)

